name: Hello World

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      #- uses: actions/checkout@v3
      - name: Run pwd
        run: echo Hello, world!
      - name: Run ls -al
        run: ls -al
